import time
from typing import Any, Dict, List, Optional


class ModelProvider:
    """Abstraction for LLM Model Providers (Mock, OpenAI, Anthropic, Local)."""
    def __init__(self, provider_id: str = "mock", name: str = "Mock Model Provider") -> None:
        self.provider_id = provider_id
        self.name = name

    def generate(self, prompt: str, model: str, max_tokens: int = 500) -> Dict[str, Any]:
        """Generates a response using the specified model."""
        start_time = time.time()
        tokens_used = min(len(prompt.split()) + 50, max_tokens)
        cost_per_token = 0.000002
        estimated_cost = tokens_used * cost_per_token

        return {
            "provider_id": self.provider_id,
            "model": model,
            "text": f"[Response generated by {model}] Processed request: {prompt[:60]}...",
            "tokens_used": tokens_used,
            "cost_usd": estimated_cost,
            "latency_seconds": round(time.time() - start_time, 4)
        }


class ModelRouter:
    """Routes agent tasks to appropriate model tiers based on task complexity."""
    def __init__(self, provider: Optional[ModelProvider] = None) -> None:
        self.provider = provider or ModelProvider()
        self.model_map = {
            "FAST": "gpt-4o-mini",
            "REASONING": "o3-mini",
            "RESEARCH": "gpt-4o",
            "TRANSLATION": "gpt-4o-mini",
            "EXTRACT": "gpt-4o-mini"
        }

    def route_and_execute(self, task_type: str, prompt: str, max_tokens: int = 500) -> Dict[str, Any]:
        model = self.model_map.get(task_type.upper(), "gpt-4o-mini")
        try:
            return self.provider.generate(prompt=prompt, model=model, max_tokens=max_tokens)
        except Exception as e:
            fallback_model = self.model_map["FAST"]
            res = self.provider.generate(prompt=prompt, model=fallback_model, max_tokens=max_tokens)
            res["fallback_triggered"] = True
            res["original_error"] = str(e)
            return res


class CostGovernor:
    """Tracks token consumption, dollar costs, and rate limits per agent and workflow."""
    def __init__(self, daily_budget_usd: float = 50.0) -> None:
        self.daily_budget_usd = daily_budget_usd
        self._total_spent_usd: float = 0.0
        self._total_tokens: int = 0
        self._agent_spend: Dict[str, float] = {}
        self._agent_tokens: Dict[str, int] = {}

    def track_usage(self, agent_id: str, tokens_used: int, cost_usd: float) -> None:
        """Records token and cost usage for an agent."""
        if self._total_spent_usd + cost_usd > self.daily_budget_usd:
            raise ValueError(
                f"Cost Governor Violation: Daily budget of ${self.daily_budget_usd:.2f} exceeded. "
                f"Current spend: ${self._total_spent_usd:.4f}, attempted: ${cost_usd:.4f}"
            )

        self._total_spent_usd += cost_usd
        self._total_tokens += tokens_used

        self._agent_spend[agent_id] = self._agent_spend.get(agent_id, 0.0) + cost_usd
        self._agent_tokens[agent_id] = self._agent_tokens.get(agent_id, 0.0) + tokens_used

    def get_agent_metrics(self, agent_id: str) -> Dict[str, Any]:
        """Returns spend and token metrics for a specific agent."""
        return {
            "agent_id": agent_id,
            "tokens_used": self._agent_tokens.get(agent_id, 0),
            "cost_usd": round(self._agent_spend.get(agent_id, 0.0), 6)
        }

    def get_global_metrics(self) -> Dict[str, Any]:
        """Returns aggregate metrics across all agents."""
        return {
            "total_tokens": self._total_tokens,
            "total_spent_usd": round(self._total_spent_usd, 6),
            "daily_budget_usd": self.daily_budget_usd,
            "remaining_budget_usd": round(self.daily_budget_usd - self._total_spent_usd, 6)
        }
