#property strict
#property version "1.2"
#property description "YarTrader MT4 Signal read-only historical bridge"
#define AUTH_ACCOUNT 143056202
string AUTH_SERVER="Alpari-Pro.ECN";
string REQ_FILE="yartrader_mt4_request.txt";
string HEARTBEAT_FILE="yartrader_mt4_heartbeat.txt";
bool Authorized(){return(!IsDemo() && AccountNumber()==AUTH_ACCOUNT && AccountServer()==AUTH_SERVER);}
int TfMinutes(string tf){if(tf=="M1")return 1;if(tf=="M5")return 5;if(tf=="M15")return 15;if(tf=="M30")return 30;if(tf=="H1")return 60;if(tf=="H4")return 240;if(tf=="D1")return 1440;if(tf=="W1")return 10080;if(tf=="MN1")return 43200;return 0;}
int TfCode(string tf){if(tf=="M1")return PERIOD_M1;if(tf=="M5")return PERIOD_M5;if(tf=="M15")return PERIOD_M15;if(tf=="M30")return PERIOD_M30;if(tf=="H1")return PERIOD_H1;if(tf=="H4")return PERIOD_H4;if(tf=="D1")return PERIOD_D1;if(tf=="W1")return PERIOD_W1;if(tf=="MN1")return PERIOD_MN1;return 0;}
void WriteHeartbeat(){if(!Authorized())return;int h=FileOpen(HEARTBEAT_FILE,FILE_WRITE|FILE_TXT|FILE_ANSI|FILE_COMMON|FILE_SHARE_READ|FILE_SHARE_WRITE);if(h==INVALID_HANDLE)return;string s=Symbol();FileWriteString(h,IntegerToString(AccountNumber())+"|"+AccountServer()+"|0|"+s+"|"+DoubleToString(MarketInfo(s,MODE_BID),Digits)+"|"+DoubleToString(MarketInfo(s,MODE_ASK),Digits)+"|"+IntegerToString((int)TimeCurrent()));FileFlush(h);FileClose(h);}
void Respond(string id,string payload){int h=FileOpen("yartrader_mt4_response_"+id+".txt",FILE_WRITE|FILE_TXT|FILE_ANSI|FILE_COMMON|FILE_SHARE_READ|FILE_SHARE_WRITE);if(h==INVALID_HANDLE)return;FileWriteString(h,id+"|"+payload);FileFlush(h);FileClose(h);}
void ProcessRequest(){if(!Authorized()||!FileIsExist(REQ_FILE,FILE_COMMON))return;int h=FileOpen(REQ_FILE,FILE_READ|FILE_TXT|FILE_ANSI|FILE_COMMON|FILE_SHARE_READ|FILE_SHARE_WRITE);if(h==INVALID_HANDLE)return;string line=FileReadString(h);FileClose(h);FileDelete(REQ_FILE,FILE_COMMON);string p[];int n=StringSplit(line,StringGetCharacter("|",0),p);if(n<2)return;string id=p[0],op=p[1];
if(op=="HISTORY"&&n>=5){string sym=p[2],tf=p[3];int bars=(int)StrToInteger(p[4]),mins=TfMinutes(tf),code=TfCode(tf);if(mins<=0||bars<=0||StringLen(sym)==0){Respond(id,"ERROR|BAD_REQUEST");return;}if(!SymbolSelect(sym,true)){Respond(id,"ERROR|SYMBOL_SELECT");return;}long serverFirst=0;SeriesInfoInteger(sym,PERIOD_M1,SERIES_SERVER_FIRSTDATE,serverFirst);datetime requestedFirst=(datetime)(TimeCurrent()-(long)bars*mins*60);datetime probe[1];int copied=0,lastErr=0,available=0;datetime oldest=0;for(int i=0;i<180;i++){ResetLastError();copied=CopyTime(sym,code,requestedFirst,1,probe);lastErr=GetLastError();available=iBars(sym,code);if(copied>0&&available>0){oldest=iTime(sym,code,available-1);if(oldest>0&&oldest<=requestedFirst)break;}if(available>0){datetime t=iTime(sym,code,available-1);if(t>0)oldest=t;}Sleep(1000);}available=iBars(sym,code);if(available<=0||oldest<=0){Respond(id,"ERROR|NO_HISTORY|"+IntegerToString(lastErr));return;}if(oldest>requestedFirst){Respond(id,"ERROR|HISTORY_INCOMPLETE|"+IntegerToString(available)+"|"+IntegerToString((int)oldest)+"|"+IntegerToString(mins)+"|"+IntegerToString((int)serverFirst)+"|"+IntegerToString(lastErr));return;}Respond(id,"OK|"+sym+"|"+tf+"|"+IntegerToString(available)+"|"+IntegerToString((int)oldest)+"|"+IntegerToString(mins)+"|"+IntegerToString((int)serverFirst));return;}
if(op=="ACCOUNT"){Respond(id,"OK|"+IntegerToString(AccountNumber())+"|"+AccountServer()+"|0|"+DoubleToString(AccountBalance(),2));return;}Respond(id,"ERROR|READ_ONLY_SIGNAL_BRIDGE");}
int OnInit(){if(!Authorized())Print("YarTrader Signal bridge waiting for authorized account/server connection");EventSetTimer(1);WriteHeartbeat();return(INIT_SUCCEEDED);}
void OnDeinit(const int reason){EventKillTimer();FileDelete(HEARTBEAT_FILE,FILE_COMMON);}
void OnTick(){WriteHeartbeat();ProcessRequest();} void OnTimer(){WriteHeartbeat();ProcessRequest();}
