"""Causal variable-duration range discovery for offline fractal research.

Candidate geometry uses only bars available at the candidate end. Future-dependent
outcomes are generated by a separate explicit labeling method and must never be
used as inference features.
"""
from __future__ import annotations

import math
from typing import Any, Dict, List, Mapping, Sequence


class FractalNestedRangeDiscovery:
    VERSION = "fractal_nested_range_discovery_v1"

    def __init__(self, min_duration: int = 8, max_duration: int = 96,
                 candidate_lengths: int = 8, min_bars: int = 8) -> None:
        if min_duration < 4 or max_duration < min_duration:
            raise ValueError("Require max_duration >= min_duration >= 4")
        if candidate_lengths < 2 or min_bars < 4:
            raise ValueError("candidate_lengths and min_bars are too small")
        self.min_duration = int(min_duration)
        self.max_duration = int(max_duration)
        self.candidate_lengths = int(candidate_lengths)
        self.min_bars = int(min_bars)

    @staticmethod
    def _clean(bars: Sequence[Mapping[str, Any]]) -> List[Dict[str, float]]:
        result = []
        for raw in bars:
            try:
                t = int(float(raw.get("time", raw.get("timestamp"))))
                o = float(raw.get("open", raw.get("Open")))
                h = float(raw.get("high", raw.get("High")))
                l = float(raw.get("low", raw.get("Low")))
                c = float(raw.get("close", raw.get("Close")))
            except (TypeError, ValueError):
                continue
            if not all(math.isfinite(v) for v in (t, o, h, l, c)):
                continue
            if min(o, h, l, c) <= 0 or h < max(o, c, l) or l > min(o, c, h):
                continue
            result.append({"time": t, "open": o, "high": h, "low": l, "close": c})
        result.sort(key=lambda b: b["time"])
        dedup = {}
        for row in result:
            dedup[row["time"]] = row
        return list(dedup.values())

    @staticmethod
    def _geometry(window: Sequence[Mapping[str, float]], start: int, end: int,
                  timeframe: str, max_duration: int) -> Dict[str, Any]:
        high = max(b["high"] for b in window)
        low = min(b["low"] for b in window)
        width = high - low
        true_ranges = []
        for i, bar in enumerate(window):
            tr = bar["high"] - bar["low"]
            if i:
                tr = max(tr, abs(bar["high"] - window[i-1]["close"]),
                         abs(bar["low"] - window[i-1]["close"]))
            true_ranges.append(tr)
        atr = sum(true_ranges) / len(true_ranges)
        closes = [b["close"] for b in window]
        path = sum(abs(closes[i] - closes[i-1]) for i in range(1, len(closes)))
        net = abs(closes[-1] - closes[0])
        efficiency = net / max(path, 1e-12)
        position = (closes[-1] - low) / max(width, 1e-12)
        width_atr = width / max(atr, 1e-12)
        compression = 1.0 / (1.0 + width_atr)
        oscillation = 1.0 - min(1.0, efficiency)
        duration_support = math.log1p(len(window)) / math.log1p(max(2, max_duration))
        score = 0.50 * compression + 0.35 * oscillation + 0.15 * duration_support
        return {
            "timeframe": timeframe, "start_index": start, "end_index": end,
            "start_time": int(window[0]["time"]), "end_time": int(window[-1]["time"]),
            "duration_bars": len(window), "high": high, "low": low,
            "mid": (high + low) / 2.0, "width": width, "atr": atr,
            "width_atr": width_atr, "close_position": max(0.0, min(1.0, position)),
            "path_efficiency": efficiency, "net_displacement": (closes[-1] - closes[0]) / max(width, 1e-12),
            "candidate_score": max(0.0, min(1.0, score)),
            "evidence_mode": "CAUSAL_CANDIDATE",
        }

    def discover_at(self, bars: Sequence[Mapping[str, Any]], timeframe: str = "UNKNOWN",
                    top_k: int = 5) -> Dict[str, Any]:
        """Return variable-length candidates ending at the latest supplied closed bar."""
        clean = self._clean(bars)
        if len(clean) < max(self.min_bars, self.min_duration):
            return {"status": "INSUFFICIENT_DATA", "timeframe": timeframe,
                    "bars_used": len(clean), "candidates": []}
        max_len = min(self.max_duration, len(clean))
        min_len = min(self.min_duration, max_len)
        if max_len == min_len:
            lengths = [max_len]
        else:
            stride = (max_len - min_len) / (self.candidate_lengths - 1)
            lengths = sorted({int(round(min_len + i * stride)) for i in range(self.candidate_lengths)})
            lengths = [n for n in lengths if min_len <= n <= max_len]
        end = len(clean) - 1
        candidates = []
        for length in lengths:
            start = end - length + 1
            candidates.append(self._geometry(clean[start:end+1], start, end,
                                              timeframe.upper(), self.max_duration))
        candidates.sort(key=lambda x: (x["candidate_score"], x["duration_bars"]), reverse=True)
        return {
            "status": "CANDIDATES_FOUND",
            "algorithm_version": self.VERSION,
            "timeframe": timeframe.upper(),
            "bars_used": len(clean),
            "decision_time": int(clean[-1]["time"]),
            "candidate_count": len(candidates),
            "candidates": candidates[:max(1, int(top_k))],
            "interpretation": "RANKED_STRUCTURAL_CANDIDATES_NOT_CONFIRMED_RANGES",
        }

    def discover_history(self, bars: Sequence[Mapping[str, Any]], timeframe: str = "UNKNOWN",
                         step: int = 1, top_k: int = 3) -> List[Dict[str, Any]]:
        """Walk forward; each result uses only history up to its decision bar."""
        if step < 1:
            raise ValueError("step must be >= 1")
        clean = self._clean(bars)
        results = []
        first_end = max(self.min_bars, self.min_duration) - 1
        for end in range(first_end, len(clean), step):
            report = self.discover_at(clean[:end+1], timeframe=timeframe, top_k=top_k)
            if report["status"] == "CANDIDATES_FOUND":
                results.append(report)
        return results

    @staticmethod
    def label_outcome(candidate: Mapping[str, Any], bars: Sequence[Mapping[str, Any]],
                      horizon: int = 24) -> Dict[str, Any]:
        """Explicit offline-only future labels; never merge into inference features."""
        if horizon < 1:
            raise ValueError("horizon must be >= 1")
        clean = FractalNestedRangeDiscovery._clean(bars)
        end = int(candidate["end_index"])
        future = clean[end+1:end+1+horizon]
        if not future:
            return {"status": "NO_FUTURE_DATA", "evidence_mode": "OFFLINE_LABEL_ONLY"}
        current = float(clean[end]["close"])
        highs = [b["high"] for b in future]
        lows = [b["low"] for b in future]
        up_i = max(range(len(future)), key=lambda i: highs[i])
        down_i = min(range(len(future)), key=lambda i: lows[i])
        up_start_i = min(range(up_i+1), key=lambda i: lows[i])
        down_start_i = max(range(down_i+1), key=lambda i: highs[i])
        atr = max(float(candidate.get("atr", 0.0)), 1e-12)
        return {
            "status": "LABELED", "evidence_mode": "OFFLINE_LABEL_ONLY",
            "label_start_time": int(clean[end]["time"]),
            "label_end_time": int(future[-1]["time"]),
            "future_up_excursion_atr": (max(highs) - current) / atr,
            "future_down_excursion_atr": (current - min(lows)) / atr,
            "up_origin_proxy_price": float(future[up_start_i]["low"]),
            "up_target_price": float(future[up_i]["high"]),
            "up_origin_proxy_bars": up_start_i + 1,
            "up_target_bars": up_i + 1,
            "down_origin_proxy_price": float(future[down_start_i]["high"]),
            "down_target_price": float(future[down_i]["low"]),
            "down_origin_proxy_bars": down_start_i + 1,
            "down_target_bars": down_i + 1,
            "label_semantics": "RETROSPECTIVE_EXTREME_PROXY_NOT_GROUND_TRUTH",
        }
