"""Hierarchical parent/child base behavior -> learned scenario -> pending-order proposal.

Research/demo-intelligence only. Never places broker orders. The engine refuses
actionable plans until historical outcome statistics are supplied and pass
minimum-sample and expectancy gates.
"""
from __future__ import annotations

from collections import defaultdict
from typing import Any, Dict, Mapping, Sequence
import math

from src.Decision.Intelligence.pending_order_planner import PendingOrderPlanner
from src.Research.Brain.multitimeframe_base_transition_engine import TIMEFRAME_ORDER, TIMEFRAME_SECONDS


def _tf_rank(tf: str) -> int:
    try:
        return TIMEFRAME_ORDER.index(tf)
    except ValueError:
        return len(TIMEFRAME_ORDER)


class HierarchicalBaseBehaviorEngine:
    """Use closed parent/child base structure and prior outcome labels only."""

    def __init__(self, planner: PendingOrderPlanner | None = None,
                 min_samples: int = 40, min_win_rate: float = 0.52,
                 min_mean_net_r: float = 0.05) -> None:
        self.planner = planner or PendingOrderPlanner()
        self.min_samples = int(min_samples)
        self.min_win_rate = float(min_win_rate)
        self.min_mean_net_r = float(min_mean_net_r)
        self._stats: Dict[str, Dict[str, float]] = {}

    @staticmethod
    def _key(tf: str, base_type: str, parent_tf: str, aligned: bool,
             relation: str = "NESTED") -> str:
        return f"{tf}|{base_type}|{parent_tf}|{relation}|{'ALIGNED' if aligned else 'OPPOSED'}"

    def learn(self, events_by_tf: Mapping[str, Sequence[Mapping[str, Any]]],
              labels: Sequence[Mapping[str, Any]], as_of: int) -> Dict[str, Any]:
        """Aggregate only outcomes whose entire label horizon ended before as_of.

        labels must be generated by the offline labeler. Ambiguous outcomes are excluded.
        """
        event_map = {e["event_id"]: e for vals in events_by_tf.values() for e in vals}
        grouped: Dict[str, list[float]] = defaultdict(list)
        eligible = 0
        for label in labels:
            event = event_map.get(label.get("event_id"))
            if not event or int(event.get("confirmation_time", 0)) >= int(as_of):
                continue
            horizon = int(label.get("label_horizon_bars", 0))
            label_end = label.get("label_end_time")
            if label_end is None or int(label_end) >= int(as_of) or horizon <= 0:
                continue
            first = label.get("first_transition")
            if first in ("ambiguous_same_bar", "horizon_expired"):
                continue
            parent_tf = str(label.get("parent_timeframe") or "NONE")
            aligned = bool(label.get("parent_aligned", False))
            if first in ("ambiguous_same_bar", "horizon_expired"):
                continue
            try:
                net_r = float(label["net_R"])
            except (KeyError, TypeError, ValueError):
                # Transition labels without a broker-costed trade outcome are diagnostic only.
                continue
            if not math.isfinite(net_r):
                continue
            relation = str(label.get("parent_relation") or "NESTED")
            key = self._key(str(event["timeframe"]), str(event["base_type"]), parent_tf, aligned, relation)
            grouped[key].append(net_r)
            eligible += 1
        self._stats = {}
        for key, values in grouped.items():
            n = len(values)
            wins = sum(value > 0 for value in values)
            win = wins / n
            se = math.sqrt(max(win * (1.0-win), 0.0) / n)
            self._stats[key] = {"samples": n, "win_rate": win, "standard_error": se,
                                "mean_net_r": sum(values)/n, "net_r_samples": n}
        return {"status": "HISTORICAL_NET_R_MODEL_AGGREGATED", "eligible_labels": eligible,
                "groups": len(self._stats), "as_of": int(as_of),
                "note": "Only completed, broker-costed net_R outcomes are eligible for actionable learning."}

    def export_stats(self) -> Dict[str, Any]:
        return {"version": 1, "min_samples": self.min_samples,
                "min_win_rate": self.min_win_rate, "min_mean_net_r": self.min_mean_net_r,
                "groups": {key: dict(value) for key, value in self._stats.items()}}

    def load_stats(self, model: Mapping[str, Any]) -> None:
        if int(model.get("version", 0)) != 1 or not isinstance(model.get("groups"), Mapping):
            raise ValueError("Unsupported or malformed Base behavior model.")
        clean: Dict[str, Dict[str, float]] = {}
        for key, raw in model["groups"].items():
            try:
                n = int(raw["samples"])
                win = float(raw["win_rate"])
                mean = float(raw["mean_net_r"])
                se = float(raw.get("standard_error", 0.0))
            except (KeyError, TypeError, ValueError) as exc:
                raise ValueError(f"Malformed model group: {key}") from exc
            if n < 0 or not all(math.isfinite(x) for x in (win, mean, se)) or not 0 <= win <= 1:
                raise ValueError(f"Invalid model statistics: {key}")
            clean[str(key)] = {"samples": n, "win_rate": win,
                               "mean_net_r": mean, "standard_error": se,
                               "net_r_samples": n}
        self._stats = clean

    def analyze(self, events_by_tf: Mapping[str, Sequence[Mapping[str, Any]]],
                quote: Mapping[str, Any], now: float,
                slippage_allowance: float = 0.0,
                commission_price_allowance: float = 0.0) -> Dict[str, Any]:
        """Return parent/child interpretation and a proposal-only conditional order plan."""
        events = [dict(e) for vals in events_by_tf.values() for e in vals
                  if int(e.get("confirmation_time", 0)) <= int(now)]
        events.sort(key=lambda e: int(e["confirmation_time"]))
        if not events:
            return {"status": "WAIT", "reason": "No closed, confirmed base events.",
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}

        children = [e for e in events if e.get("timeframe") in ("M15", "M5")]
        if not children:
            return {"status": "WAIT", "reason": "No confirmed M15/M5 child base.",
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        child = children[-1]
        max_age = 8 * TIMEFRAME_SECONDS.get(str(child.get("timeframe")), 60)
        if float(now) - int(child.get("confirmation_time", 0)) > max_age:
            return {"status": "WAIT", "reason": "Latest child Base is stale; wait for a fresh confirmed Base event.",
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        child_direction = int(child.get("exit_direction", 0))
        if child_direction not in (-1, 1):
            return {"status": "WAIT", "reason": "Child Base has no valid confirmed departure direction.",
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        direction = "BUY" if child_direction > 0 else "SELL"
        nested_parents, transition_parents = [], []
        child_start = int(child.get("base_start_time", 0))
        child_end = int(child.get("base_end_time", 0))
        child_confirm = int(child.get("confirmation_time", 0))
        child_low, child_high = float(child.get("base_low", -math.inf)), float(child.get("base_high", math.inf))
        child_mid = float(child.get("base_mid", (child_low+child_high)/2))
        for p in events:
            parent_tf_candidate = str(p.get("timeframe", ""))
            if _tf_rank(parent_tf_candidate) >= _tf_rank(str(child.get("timeframe"))):
                continue
            parent_confirm = int(p.get("confirmation_time", 0))
            if parent_confirm > child_confirm:
                continue
            seconds = TIMEFRAME_SECONDS.get(parent_tf_candidate, 60)
            if child_confirm - parent_confirm > 24 * seconds:
                continue
            p_low, p_high = float(p.get("base_low", -math.inf)), float(p.get("base_high", math.inf))
            p_mid = float(p.get("base_mid", (p_low+p_high)/2))
            starts_before_child = int(p.get("base_start_time", 0)) <= child_start
            contains_time = int(p.get("base_end_time", 0)) >= child_end
            contains_price = p_low <= child_low and p_high >= child_high
            if starts_before_child and contains_time and contains_price:
                nested_parents.append(p)
                continue
            overlaps_zone = child_low <= p_high and child_high >= p_low
            directional_corridor = child_mid >= p_mid if child_direction > 0 else child_mid <= p_mid
            if starts_before_child and (overlaps_zone or directional_corridor):
                transition_parents.append(p)
        if nested_parents:
            parent = max(nested_parents, key=lambda e: (_tf_rank(str(e["timeframe"])), int(e["confirmation_time"])))
            parent_relation = "NESTED"
        elif transition_parents:
            parent = max(transition_parents, key=lambda e: (_tf_rank(str(e["timeframe"])), int(e["confirmation_time"])))
            parent_relation = "TRANSITION_CONTEXT"
        else:
            parent, parent_relation = None, "NONE"
        aligned = bool(parent and int(parent.get("exit_direction", 0)) == child_direction)
        parent_tf = str(parent.get("timeframe")) if parent else "NONE"
        micro_candidates = [
            e for e in events
            if e.get("timeframe") == "M1"
            and child_confirm <= int(e.get("confirmation_time", 0)) <= int(now)
            and int(now) - int(e.get("confirmation_time", 0)) <= 8 * TIMEFRAME_SECONDS["M1"]
            and int(e.get("exit_direction", 0)) == child_direction
            and ((float(quote.get("ask", 0.0)) > child_high) if child_direction > 0
                 else (float(quote.get("bid", 0.0)) < child_low))
        ]
        micro = max(micro_candidates, key=lambda e: int(e["confirmation_time"])) if micro_candidates else None
        key = self._key(str(child["timeframe"]), str(child["base_type"]), parent_tf, aligned, parent_relation)
        stat = self._stats.get(key)

        context = {
            "parent_base_id": parent.get("event_id") if parent else None,
            "parent_timeframe": parent_tf,
            "parent_relation": parent_relation,
            "child_base_id": child.get("event_id"),
            "child_timeframe": child.get("timeframe"),
            "parent_child_alignment": "ALIGNED" if aligned else ("OPPOSED" if parent else "NO_PARENT"),
            "parent_base_type": parent.get("base_type") if parent else None,
            "child_base_type": child.get("base_type"),
            "micro_base_id": micro.get("event_id") if micro else None,
            "micro_timeframe": "M1" if micro else None,
            "micro_direction": micro.get("exit_direction") if micro else None,
            "known_at": int(now),
            "causal_cutoff": max(int(child.get("confirmation_time", 0)),
                                 int(parent.get("confirmation_time", 0)) if parent else 0),
        }
        if not parent or not aligned:
            return {"status": "WAIT", "reason": "A valid, aligned higher-timeframe parent and lower-timeframe child are required.",
                    "structure": context, "learning": stat,
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        if not micro:
            return {"status": "WAIT", "reason": "No fresh, direction-aligned M1 Base departure confirms timing outside the child zone.",
                    "structure": context, "learning": stat,
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        if not stat or int(stat["samples"]) < self.min_samples:
            return {"status": "WAIT", "reason": "Insufficient prior, outcome-labeled examples for this parent/child pattern.",
                    "structure": context, "learning": stat,
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        if stat["win_rate"] < self.min_win_rate:
            return {"status": "WAIT", "reason": "Historical net-R win rate does not pass the configured research gate.",
                    "structure": context, "learning": stat,
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}
        if stat.get("mean_net_r") is None or float(stat["mean_net_r"]) < self.min_mean_net_r:
            return {"status": "WAIT", "reason": "Historical broker-costed net expectancy is unavailable or below threshold.",
                    "structure": context, "learning": stat,
                    "order_plan": self.planner.plan({}, quote, now).to_dict()}

        low, high = float(child["base_low"]), float(child["base_high"])
        atr = float(child["base_atr"])
        entry = (low + high) / 2.0
        target_candidates = []
        for e in events:
            if e.get("timeframe") != child.get("timeframe") or e.get("event_id") == child.get("event_id"):
                continue
            mid = float(e.get("base_mid", (float(e["base_low"])+float(e["base_high"]))/2))
            if direction == "BUY" and mid > high:
                target_candidates.append((mid-entry, e))
            elif direction == "SELL" and mid < low:
                target_candidates.append((entry-mid, e))
        invalidation = low-0.15*atr if direction == "BUY" else high+0.15*atr
        target_base = min(target_candidates, key=lambda x: x[0])[1] if target_candidates else None
        if target_base is not None:
            target = float(target_base.get("base_low") if direction == "BUY" else target_base.get("base_high"))
            target_source = "PREVIOUSLY_KNOWN_DESTINATION_BASE"
        else:
            target = entry + (1 if direction == "BUY" else -1) * 3.0 * abs(entry-invalidation)
            target_source = "STRUCTURAL_3R_FALLBACK"
        scenario = {
            "direction": direction, "setup_type": "RETEST", "zone_low": low, "zone_high": high,
            "invalidation": invalidation,
            "target": target, "target_source": target_source, "atr": atr, "confidence": 100.0*stat["win_rate"],
            "expires_at": float(now)+(8*900 if child.get("timeframe") == "M15" else 8*300),
            "slippage_allowance": slippage_allowance,
            "commission_price_allowance": commission_price_allowance,
        }
        plan = self.planner.plan(scenario, quote, now).to_dict()
        return {"status": "ORDER_PROPOSAL" if plan["status"] == "PROPOSED" else "WAIT",
                "reason": "Learned parent/child Base pattern passed research gates; proposal only." if plan["status"] == "PROPOSED" else plan["reason"],
                "structure": context, "learning": stat,
                "target_base_id": target_base.get("event_id") if target_base else None,
                "target_source": target_source,
                "scenario": scenario, "order_plan": plan, "execution_enabled": False}
